name: CI/CD Pipeline Standard

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Descarcă codul pe serverul din cloud
    - name: Checkout cod
      uses: actions/checkout@v4

    # 2. Se loghează pe contul tău de Docker Hub usando secretele configurate
    - name: Autentificare Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # 3. Construiește imaginea Docker și o urcă direct pe Docker Hub
    - name: Build și Push Imagine Docker
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: claudiulatea2/licenta-app:latest
